spring:
  cloud:
    gateway:
      routes:
        - id: user-svc
          uri: lb://user-svc
          predicates:
            - Path=/user/**
        - id: review-svc
          uri: lb://review-svc
          predicates:
            - Path=/review/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


management:
  #enable spring actuator,health and prometheus
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    show:
      details: always
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0

logging:
  file:
    name: /var/log/springboot/api-gateway-svc.log
  level:
    root: info



