apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "user-reviews.fullname" . }}
  namespace: {{.Values.service.namespace}}
  labels:
    {{- include "user-reviews.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "user-reviews.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "user-reviews.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "user-reviews.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - name: log-volume
              mountPath: /var/log/springboot # Directory for application logs
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{.Values.microservice.DbSecrets}}
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{.Values.microservice.DbSecrets}}
                  key: DB_PASSWORD        
            - name: Environment
              valueFrom:
                configMapKeyRef:
                  name: {{.Values.microservice.configmap}}
                  key: Environment    
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{.Values.microservice.configmap}}
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{.Values.microservice.configmap}}
                  key: DB_PORT
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{.Values.microservice.configmap}}
                  key: DB_DATABASE
            - name: APP_CONFIG_DIR
              valueFrom:
                configMapKeyRef:
                  name: {{.Values.microservice.configmap}}
                  key: APP_CONFIG_DIR
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{.Values.microservice.configmap}}
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_ZIPKIN_BASE_URL
              value: "http://zipkin.tracing.svc.cluster.local:9411"
            - name: SPRING_SLEUTH_SAMPLER_PROBABILITY
              value: "1.0"
            - name: ZIPKIN_HOST
              value: "zipkin"
            - name: ZIPKIN_PORT
              value: "9411"
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: log-volume
              mountPath: /var/log/springboot # Directory for application logs
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      # Shared volume for logs between the app and Promtail
      volumes:
        - name: log-volume
          emptyDir: {}

        # ConfigMap for Promtail configuration
        - name: promtail-config
          configMap:
            name: promtail-config