apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloud-config-server.fullname" . }}
  namespace: {{.Values.service.namespace}}
  labels:
    app: {{.Values.service.serviceLabel}}
    job: {{.Values.service.jobName}}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cloud-config-server.selectorLabels" . | nindent 4 }}
