apiVersion: v1
kind: Service
metadata:
  name: {{ include "service-registry.name" . }}
  namespace: {{.Values.service.namespace}}
  labels:
    {{- include "service-registry.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "service-registry.selectorLabels" . | nindent 4 }}
