apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: {{.Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:8.3.0
          restart: always
          name: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: socialmedia
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: db-secrets
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: db-secrets
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: DB_USER
                  name: db-secrets
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data
            - mountPath: /docker-entrypoint-initdb.d
              name: mysql-initdb-config
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: mysql-initdb-config
          configMap:
            name: mysql-initdb-config        
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: {{.Values.global.namespace }}
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: mysql-pv
    namespace: {{.Values.global.namespace }}
spec:
  storageClassName: 'standard'
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: {{.Values.global.namespace }}
spec:
  storageClassName: 'standard'
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
  namespace: {{.Values.global.namespace }}
data:
  initdb.sql: |
    SET sql_safe_updates=0;

    CREATE DATABASE IF NOT EXISTS socialmedia DEFAULT CHARACTER SET utf8;

    delete from mysql.user where user = 'sjala';
    commit;

    CREATE USER 'sjala' identified by 'JalaJala123';

    GRANT SELECT ON socialmedia.* TO 'sjala';
    GRANT INSERT ON socialmedia.* TO 'sjala';
    GRANT UPDATE ON socialmedia.* TO 'sjala';
    GRANT DELETE ON socialmedia.* TO 'sjala';
    GRANT EXECUTE ON socialmedia.* TO 'sjala';

    GRANT ALL PRIVILEGES ON *.* TO 'sjala'@'%';
