server:
  port: 8082
  servlet:
    context-path: /user


eureka:
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY-SVC:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: user-svc
  config:
   import: configserver:http://${CONFIG-SERVER:localhost}:8088
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://172.17.64.1:3306/socialmedia}
    #SPRING_DATASOURCE_URL - jdbc:mysql://${DB_HOST}:${DB_PORT}/socialmedia
    username: ${DB_USER:sjala}
    password: ${DB_PASSWORD:JalaJala123}
  sql:
    init:
      platform: mysql
  #hibernate.dialect=org.hibernate.dialect.MySQLInnoDBDialect
  security:
    user:
      name: admin
      password: admin
  #automatically create/update tables
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

resilience4j:
  circuitBreaker:
    instances:
      getUserById:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      getUserById:
        maxAttempts: 5
        waitDuration: 10s
  rateLimiter:
    instances:
      getUserById:
        registerHealthIndicator: false
        limitForPeriod: 10
        limitRefreshPeriod: 10s
        timeoutDuration: 3s