server:
  port: 8088

spring:
  application:
    name: config-server
  profiles:
    active:
      - native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sriharijala/config-server
          clone-on-start: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY-SVC:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO

management:
  tracing:
    sampling:
      probability: 1.0
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
