apiVersion: v1
kind: Service
metadata:
  name: {{ include "config-server.fullname" . }}
  namespace: {{.Values.microservice.namespace}}
  labels:
    {{- include "config-server.labels" . | nindent 4 }}
    app : {{.Values.microservice.serviceLabel}}
    job : {{.Values.microservice.jobName}}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "config-server.selectorLabels" . | nindent 4 }}
