apiVersion: v1
kind: ConfigMap
metadata:
  name:  user-reviews.properties
  namespace: {{.Values.global.namespace}}
data:
  Environment: "prod"
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_DATABASE: "socialmedia"
  APP_CONFIG_DIR: "/usr/app"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/socialmedia"
  CONFIG-SERVER: config-server
  REGISTRY-SVC: registry-svc
  USER-SVC: user-svc
  REVIEW-SVC: user-svc
  API-GATEWAY: api-gateway
  ZIPKIN: zipkin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: {{.Values.global.namespace}}
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    clients:
      - url: http://loki:3100/loki/api/v1/push  # Loki server URL

    positions:
      filename: /var/log/positions.yaml

    scrape_configs:
      - job_name: spring-boot-logs
        static_configs:
          - targets:
              - localhost
            labels:
              job: spring-boot
              __path__: /var/log/springboot/*.log  # Path to log files
      - job_name: system
          - targets:
              - "localhost"
            labels:
              job: varlogs
              __path__: /var/log/*log

