apiVersion: v1
kind: Service
metadata:
  name: {{ include "review-svc.name" . }}
  namespace: {{.Values.global.namespace }}
  labels:
    {{- include "review-svc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "review-svc.selectorLabels" . | nindent 4 }}
