management:
  context-path: /user/actuator
  #enable spring actuator,health and prometheus
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    tags:
      application: user-svc
  tracing:
    sampling:
      probability: 1.0
    enable:
      web:
        client:
          requests: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/socialmedia
    username: sjala
    password: JalaJala123
  sql:
    init:
      platform: mysql
#hibernate.dialect=org.hibernate.dialect.MySQLInnoDBDialect
  security:
    user:
      name: admin
      password: admin
#automatically create/update tables
  jpa:
    hibernate:
      ddl-auto: update
  show-sql: true

springdoc:
  swagger-ui.path: /swagger-ui.html
  api-docs:
    path: /api-docs

logging:
  file:
    name: /var/log/springboot/user-svc.log
  level:
    root: INFO
    org:
      springframework:
        web: ERROR
        orm:
          jpa: ERROR
      transaction: ERROR
    # for Hibernate only
    hibernate: ERROR

# OTLP exporter endpoint - Jaeger, Tempo, or any OpenTelemetry-compatible backend
#otel:
#  traces:
#    exporter: otlp
#  exporter:
#    otlp:
#      endpoint: http://tempo:4317  # Replace with 'jaeger:14250' for Jaeger in OTLP
#  resource:
#    attributes:
#      service.name: user-reviews-svc