server:
  port: 9000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY-SVC:localhost}:8761/eureka/

spring:
  application:
    name: api-gateway
  config:
    import: configserver:http://${config-server:localhost}:8088
  cloud:
    gateway:
      routes:
        - id: api-gateway
          uri: lb://api-gateway
          predicates:
            - Path=/eureka/**
        - id: user-svc
          uri: lb://user-svc
          predicates:
            - Path=/user/**
        - id: review-svc
          uri: lb://review-svc
          predicates:
            - Path=/review/**
